### ISSUE TITLE
image

### ISSUE THREAD

**Issue by beomsu7** [beomsu7/mavros_simple_control#1]
![image1](https://user-images.githubusercontent.com/72853382/99606499-37af0f00-2a4d-11eb-892a-a3bf923be681.png)

**Comment by atmaca11** [comment]
Hi , I need your help and how can I reach you ? 
E-mail or whatsapp ?

**Comment by beomsu7** [comment]
Actually this is very simple and basic works, so mayb you can do it easily
but if you need something more, then email would be better
habemsu@koreatech.ac.kr
